[package]
name = "auto"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "automl"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
automl = "0.2.6"
smartcore = "0.2.1"


